### ISSUE TITLE
Bower Components also needs to search in sassLibFoldersGlobStr

### ISSUE THREAD

**Issue by kohenkatz** [strarsis/sass-include-paths#3]
Here are some examples of popular bower components that are found using `sassLibFoldersGlobStr` but not using `sassFoldersGlobStr`:

 - `bower_components/bootstrap-sass/assets/stylesheets`
 - `bower_components/font-awesome/scss`

In truth, it would be nicest if there was some way that we could easily override the glob string in the `opts` argument.

**Comment by strarsis** [comment]
This has been fixed now with release v4.4.0.

I will add options to the module so the globs can be overriden.

**Comment by kohenkatz** [comment]
:+1:

**Comment by strarsis** [comment]
https://github.com/strarsis/sass-include-paths/issues/4
